
services:
  app:
    build:
      context: .
    command: bash start-dev.sh
    environment:
      DB_URL: jdbc:postgresql://db:5432/barbershop
      DB_USER: tester
      DB_PASSWORD: @Te3t!
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/barbershop-vol:z
    depends_on:
      - db
    networks:
      - barbershop-net
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: @Te3t!
      POSTGRES_DB: barbershop
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "5432:5432"
    networks:
      - barbershop-net
networks:
  barber-shop-net:
    name: barbershop-net
    external: true
volumes:
  db:
